name: Package and Release AddOn

# 触发条件：当你推送一个以 'v' 开头的标签时，例如 v1.0.0
on:
  push:
    tags:
      - "v*"

# 环境变量：从刚才设置的 Secrets 中读取 Token
env:
  CF_API_KEY: ${{ secrets.CF_API_KEY }}
  GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 允许创建 Release
      packages: write # 可选，如果不需要可删除
    steps:
      # 1. 检出你的代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2. 使用 BigWigs 打包工具
      - name: Package and Upload
        uses: BigWigsMods/packager@v2
